BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: input_number
        BoxLayout:
            orientation: 'vertical'
            Button:
                text: 'Up'
            Button:
                text: 'Down'
    Button:
        text: 'Convert mi to km'
        on_press: app.handle_conversion(input_number.text)
    Label:
        text: 'test'
        id: output_label
        color: (1, 1, 0, 1)


